# nixpacks.toml

[phases.setup]
# Install system packages that yt-dlp needs for best performance and resilience.
# openssl & ca-certificates are crucial for TLS/SSL fingerprinting used in impersonation.
aptPkgs = ["ffmpeg", "brotli", "openssl", "ca-certificates"]

[start]
# The command to run your FastAPI application.
cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT"
